#!/bin/bash


function(){
   journalctl --list-boots
      
}
function

# Purpose - Display a menu on screen

function show_menu(){

date

echo "---------------------------"

echo " Boot Log"

echo "---------------------------"

echo "1. Operating system info"

echo "2. Hostname and dns info"

echo "3. Network info"


}

   
