#!/bin/bash

journalctl --list-boots >> LOG1="LOG 1"
     
# Purpose - Display a menu on screen

function show_menu(){

date

echo "---------------------------"

echo " Boot Log"

echo "---------------------------"

echo "$LOG1"

echo "2. Hostname and dns info"

echo "3. Network info"


}

   
